### ISSUE TITLE
Error during sync

### ISSUE THREAD

**Issue by OptimusGREEN** [atoy3731/adguard-sync#8]
Hi,

I'm just trying out AGHsync for the first time and I'm getting this error but have no idea where to go from here.

```
Running Adguard Sync for 'http://10.79.1.108' => 'http://10.79.8.2'..,
Traceback (most recent call last):,
  File "app.py", line 89, in <module>,
    custom_rules.reconcile(primary_filtering_status, secondary_filtering_status, ADGUARD_SECONDARY, secondary_cookie),
  File "/opt/app/custom_rules/__init__.py", line 53, in reconcile,
    secondary_custom_rules = _get_custom_rules(secondary_filtering_status),
  File "/opt/app/custom_rules/__init__.py", line 17, in _get_custom_rules,
    custom_rules_str = '\n'.join(custom_rules_array),
TypeError: can only join an iterable,
```

Any help would be appreciated.

**Comment by OptimusGREEN** [comment]
dunno how, but this issue is resolved

**Comment by taylorcjensen** [comment]
I am experiencing the same problem. Did you really do nothing? My container stops after this error, and I have to manually restart it - with the same error repeating.

```
Running Adguard Sync for 'http://192.168.0.2:80' => 'http://192.168.0.3:80'..

Traceback (most recent call last):

  File "app.py", line 89, in <module>

    custom_rules.reconcile(primary_filtering_status, secondary_filtering_status, ADGUARD_SECONDARY, secondary_cookie)

  File "/opt/app/custom_rules/__init__.py", line 52, in reconcile

    primary_custom_rules = _get_custom_rules(primary_filtering_status)

  File "/opt/app/custom_rules/__init__.py", line 17, in _get_custom_rules

    custom_rules_str = '\n'.join(custom_rules_array)

TypeError: can only join an iterable
```

**Comment by taylorcjensen** [comment]
Seems to be related to custom rules, if I set `SYNC_CUSTOM_RULES` to false the sync completes without issue.
